FROM archlinux:latest

# Install dependencies and retrieve seal-python files
RUN pacman -Syyuu \
    base-devel \
    cmake \
    clang \
    git \
    python \
    python-pip \
    python-sphinx \
    python-sphinx-argparse \
    python-sphinx_rtd_theme \
    python-configargparse \
    --noconfirm

RUN git clone -b 3.4.5-rlatest https://github.com/DreamingRaven/seal-python

# Build SEAL packages in seal-python
RUN cd /seal-python/SEAL/native/src && \
    cmake . && \
    make && \
    make install && \
    echo "/usr/local/lib" >> /etc/ld.so.conf.d/seal.conf

# Install requirements of seal-python
RUN cd /seal-python && \
    pip3 install -r requirements.txt

# Build pybind11
RUN cd /seal-python/pybind11 && \
    mkdir build && \
    cd /seal-python/pybind11/build && \
    cmake .. && \
    make check -j 4 && \
    make install

# Package wrapper
RUN cd /seal-python && \
    python3 setup.py build_ext -i && \
    python3 setup.py install

# Clean-up
RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# copy our files in
COPY . /python-fhe
