#!/usr/bin/env bash

# @Author: GeorgeRaven <archer>
# @Date:   2020-05-22T10:08:17+01:00
# @Last modified by:   archer
# @Last modified time: 2021-03-15T11:51:19+00:00
# @License: please see LICENSE file in project root

sudo docker build -t archer/fhe -f Dockerfile_archlinux .  || exit 1 # this uses our docker
# sudo docker build -t archer/fhe -f Dockerfile_archlinux --no-cache .

# build the docs
sudo docker run -v ${PWD}/docs/build/:/app/docs/build -it archer/fhe make -C ./docs html
