#!/usr/bin/env bash

sudo docker build -t archer/fhe -f Dockerfile_archlinux .
# sudo docker build -t archer/fhe -f Dockerfile_archlinux --no-cache .
sudo docker run --gpus all -it archer/fhe /python-fhe/fhe.py
sudo docker run --gpus all -it archer/fhe make -C /python-fhe/docs html
# sudo docker run --gpus all -it archer/fhe bash
