#!/usr/bin/env bash

# @Author: GeorgeRaven <archer>
# @Date:   2020-05-22T10:08:17+01:00
# @Last modified by:   archer
# @Last modified time: 2021-02-22T15:59:19+00:00
# @License: please see LICENSE file in project root

sudo docker build -t archer/fhe -f Dockerfile_archlinux .  || exit 1 # this uses our docker
# sudo docker build -t archer/fhe -f Dockerfile_archlinux --no-cache .

sudo docker run --cpus=2 --memory 8G -it archer/fhe /python-fhe/fhe/reseal.py
sudo docker run --cpus=2 --memory 8G -it archer/fhe /python-fhe/fhe/rearray.py
sudo docker run --cpus=2 --memory 18G -it archer/fhe /python-fhe/fhe/nn/layer/cnn.py
#sudo docker run --cpus=2 --memory 12G -it archer/fhe /python-fhe/fhe/nn/layer/ann.py
#sudo docker run -it archer/fhe make -C /python-fhe/docs html
# sudo docker run --gpus all -it archer/fhe bash
