#!/usr/bin/env bash

# @Author: GeorgeRaven <archer>
# @Date:   2020-05-22T10:08:17+01:00
# @Last modified by:   archer
# @Last modified time: 2021-08-19T10:10:00+01:00
# @License: please see LICENSE file in project root

sudo docker build -t archer/fhe-jupyter -f Dockerfile_archlinux_jupyter . || exit 1 # this builds our jupyter docker container

# run jupyter lab container
sudo docker run -p 127.0.0.1:8888:8888 -v "${PWD}/examples":/app/examples -it archer/fhe-jupyter
