#!/usr/bin/env bash

# @Author: GeorgeRaven <archer>
# @Date:   2020-05-22T10:08:17+01:00
# @Last modified by:   archer
# @Last modified time: 2021-07-24T15:15:35+01:00
# @License: please see LICENSE file in project root

sudo docker build -t archer/fhez -f Dockerfile_archlinux .  || exit 1 # this uses our docker
# sudo docker build -t archer/fhe -f Dockerfile_archlinux --no-cache . || exit 1

sudo docker run --cpus=2 --memory 24G -it archer/fhez python -m unittest discover -p "*_test.py" # -s fhez/

# # test each component library
# sudo docker run --cpus=2 --memory 8G -it archer/fhez ./fhez/reseal.py
# sudo docker run --cpus=2 --memory 8G -it archer/fhez ./fhez/rearray.py
#
# # test computational graph and components
# sudo docker run --cpus=2 --memory 24G -it archer/fhez ./fhez/nn/nn.py
